trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # or use your self-hosted agent

variables:
  dockerHubImage: 'nginx:latest'                  # Example Docker Hub image
  acrLoginServer: 'acrbojtest.azurecr.io'              # Your ACR login server
  acrImageName: 'nginx'                         # Image name in ACR
  acrImageTag: 'latest'                           # Image tag in ACR

stages:
  - stage: PushToACR
    jobs:
      - job: PullTagPush
        steps:

        - task: DockerInstaller@0
          inputs:
            dockerVersion: '28.3.0'

        - script: |
            echo "Pulling from Docker Hub..."
            docker pull $(dockerHubImage)

            echo "Tagging image for ACR..."
            docker tag $(dockerHubImage) $(acrLoginServer)/$(acrImageName):$(acrImageTag)
          displayName: 'Pull and Tag Image'

        - task: Docker@2
          displayName: 'Login to Azure Container Registry'
          inputs:
            command: login
            containerRegistry: 'konjur-azure-container-registry-connection'

        - script: |
            echo "Pushing image to ACR..."
            docker push $(acrLoginServer)/$(acrImageName):$(acrImageTag)
          displayName: 'Push Image to ACR'
